#### PARROTS main params ####
input_options: 
  input_pdb: ./inputs/PDBs/4zqk_PD1_rx.pdb
  base_dir: .
  template_fasta: ./inputs/4ZQK_pd1_truncated.fasta
  binder_chain: "A" 

pipeline_options:
  n_iterations:    1               # Int; Default 1
  run_rfd: true
  run_design: false
  run_predict: false

environment: environment.yaml

################################## WORKSHOP STEP 2 ##################################

### PARROTS RFD scaffold generation params ####
rfd_options:
  output_dir: ""                  # Str; Defaults to <base_dir>/RFDiffusion_output
  contigs: '[A1-106/0 70-120]'    # Str
  hotspot_res: '[A32,A86,A94]'    # Str 
  num_designs: 10                 # Int; Default 5
  output_prefix: ""               # Str; Defaults to None

################################## WORKSHOP STEP 3 ##################################

#### PARROTS Design params ####
design_options: 
  input_dir: ""                   # Str; Defaults to <base_dir>/RFDiffusion_output/passed
  output_dir: ""                  # Str; Defaults to <base_dir>/Design_output
  design_mode: ""                 # Str; Default mpnn; options: mpnn, rosetta
  use_backrub: false              # Bool; Default false
  n_trials:                       # Int; Default 4
  n_pass:                         # Int; Default 3
  input_is_relaxed: true          # Bool; Default true (input to design step is already relaxed; set to False if designing AF3 output directly)
  bias: ""                        # Str; Default None; path to .jsonl dictionary file

################################## WORKSHOP STEP 4 ##################################

### PARROTS Structural Prediction params ####
predict_options:
  input_dir: ""                   # Str; Defaults to <base_dir>/Design_output/filtered_step_2
  output_dir: ""                  # Str; Defaults to <base_dir>/Prediction_output
  predict_mode:                   # Str; Default AF3; Other options: Chai, AF3_Chai
  bootstrap_msa:                  # Bool; Default True (PARROTS will use the target MSA generated for the first structural prediction for all subsequent predictions; Makes it run faster)
  add_hsa:                        # Bool; Default False
  linker:                         # Str; Default ""
  binder_position:                # Str; Default "C"; Binder position relative to HSA (if "C" it's a C-terminal fusion)
  batch_size:                     # Int; Default 30
  run_ipsae:                      # Bool; Default True






  