# 02_test_config.yaml (For step 20.2)

#### PARROTS main params ####
input_options: 
  input_pdb: ../Example/inputs/PD1_PDBs/4zqk_PD1_rx.pdb # already pre-set for this exercise
  base_dir: .
  template_fasta: ./inputs/4ZQK_pd1_truncated.fasta     # already pre-set for this exercise
  binder_chain: "A" 

pipeline_options:
  n_iterations:                                         # Int; Default 1
  run_rfd: false
  run_design: false
  run_predict: true                                     # prediction only

environment: environment.yaml

# ### PARROTS RFD scaffold generation params ####
# rfd_options:
#   contigs: '[A1-106/0 70-120]'                          # KEEP THIS UNLESS YOU WANNA CHANGE BINDER LEN
#   hotspot_res:                                          # Str (eg. '[A32,A86,A94]') ADD YOURS
#   num_designs: 10                                       # Int; Default 5

# #### PARROTS Design params ####
# design_options: 
#   n_trials: 3                                           # Int; Default 4
#   n_pass: 2                                             # Int; Default 3

### PARROTS Structural Prediction params ####
# All default
predict_options:
  run_ipsae: true                                       # Bool; Default True